"""Classify DLD project_name strings into building-identity types.

DLD's project_name_en column is overloaded — it contains real building names
("SIRAJ TOWER"), area names ("JUMEIRAH VILLAGE CIRCLE"), developer names
("DAMAC HILLS"), master-project labels ("ARABIAN RANCHES"), and various
generic-term combinations. This module separates them so the Building X-Ray
can show truthful display strings instead of misleading every row as a
distinct building.

Classifier output:
    ('real_building',  name)          # likely a true tower/villa name
    ('sub_project',    name)          # contains the master project name
                                      # ("DAMAC HILLS - CARSON")
    ('master_project', master_name)   # name == master project label
    ('developer_name', fallback)      # name is a developer label
    ('area_name',      fallback)      # name is just the area name
    ('no_name',        None)          # blank input

The blacklist JSON is generated by hand at build time from prod data — see
app/data/building_name_blacklist.json.
"""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Optional

# Resolve to backend/app/data/building_name_blacklist.json regardless of
# where this module is imported from.
_BLACKLIST_PATH = (
    Path(__file__).resolve().parent.parent / "app" / "data" / "building_name_blacklist.json"
)


@lru_cache(maxsize=1)
def _blacklists() -> tuple[frozenset[str], frozenset[str], frozenset[str]]:
    data = json.loads(_BLACKLIST_PATH.read_text())
    areas = frozenset((a or "").strip().upper() for a in data.get("areas", []))
    devs = frozenset((d or "").strip().upper() for d in data.get("developers", []))
    masters = frozenset((m or "").strip().upper() for m in data.get("master_projects", []))
    return areas, devs, masters


# Type codes — keep these stable; they're persisted to dld_buildings.building_name_type.
TYPE_REAL_BUILDING = "real_building"
TYPE_SUB_PROJECT = "sub_project"
TYPE_MASTER_PROJECT = "master_project"
TYPE_DEVELOPER_NAME = "developer_name"
TYPE_AREA_NAME = "area_name"
TYPE_NO_NAME = "no_name"

# Types that should feed building-level analytics (real towers / specific
# sub-projects). Other types are area-level signal at best.
IDENTIFIABLE_TYPES = frozenset({TYPE_REAL_BUILDING, TYPE_SUB_PROJECT})


def classify_building_name(
    project_name: Optional[str],
    master_project: Optional[str],
    area_name: Optional[str],
) -> tuple[Optional[str], str]:
    """Return (clean_name, type) per the user-spec rules.

    clean_name is the BEST string to use as the building identity:
      - real_building / sub_project → the original project_name
      - master_project              → the master_project label
      - developer_name / area_name  → fall back to master or area
      - no_name                     → None

    Caller decides how to display (see display_name() below).
    """
    if not project_name or not project_name.strip():
        return None, TYPE_NO_NAME
    name_upper = project_name.strip().upper()
    areas_bl, devs_bl, masters_bl = _blacklists()

    # Area collision: name is verbatim an admin sector / community name.
    if name_upper in areas_bl:
        return (master_project or area_name), TYPE_AREA_NAME

    # Developer collision: substring either way matches a registered developer.
    for dev in devs_bl:
        if not dev:
            continue
        if dev in name_upper or name_upper in dev:
            return (master_project or area_name), TYPE_DEVELOPER_NAME

    # Master project: name equals master_project verbatim.
    if master_project and master_project.strip().upper() == name_upper:
        return master_project, TYPE_MASTER_PROJECT

    # Also check the global master_projects blacklist (caught when the row
    # lacks its own master_project value but the name happens to match a
    # known master-project label).
    if name_upper in masters_bl:
        return (master_project or area_name), TYPE_MASTER_PROJECT

    # Sub-project: name contains the master_project label
    # ("DAMAC HILLS - CARSON" → carson).
    if master_project and master_project.strip().upper() in name_upper:
        return project_name, TYPE_SUB_PROJECT

    # Default: looks like a real building name.
    return project_name, TYPE_REAL_BUILDING


def display_name(
    project_name: Optional[str],
    master_project: Optional[str],
    area_name: Optional[str],
    clean_name: Optional[str],
    type_code: str,
) -> str:
    """Human-facing display string per the user-spec rendering rules."""
    if type_code == TYPE_REAL_BUILDING:
        return project_name or "Unspecified building"
    if type_code == TYPE_SUB_PROJECT:
        return f"{project_name} (part of {master_project})"
    if type_code == TYPE_MASTER_PROJECT:
        return f"{clean_name or master_project} 🏘️ community"
    if type_code == TYPE_DEVELOPER_NAME:
        # project_name was a developer label; surface the area context
        return f"{area_name or 'Unspecified area'} 🏗️ {project_name} area"
    if type_code == TYPE_AREA_NAME:
        return area_name or (project_name or "Unspecified area")
    # no_name
    return f"Unspecified unit in {area_name or 'Dubai'}"


def is_identifiable(type_code: str) -> bool:
    return type_code in IDENTIFIABLE_TYPES
