"""Initial schema with areas and market_snapshots

Revision ID: 6100427391fb
Revises: 
Create Date: 2026-05-27 17:37:03.721920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6100427391fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_arabic', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('emirate', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('area_type', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_name'), 'areas', ['name'], unique=True)
    op.create_table('market_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('area_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('avg_sale_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('avg_price_per_sqft', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('avg_annual_rent', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('rental_yield', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('occupancy_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('appreciation_1y', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('appreciation_3y', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('transaction_volume', sa.Integer(), nullable=True),
    sa.Column('demand_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('investment_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('data_source', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_snapshots_area_id'), 'market_snapshots', ['area_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_snapshots_area_id'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index(op.f('ix_areas_name'), table_name='areas')
    op.drop_table('areas')
    # ### end Alembic commands ###
